// This file is automatically generated during build. Do not edit manually.
class Environment {
  static const String stravaClientId = String.fromEnvironment('STRAVA_CLIENT_ID', defaultValue: '');
  static const String stravaClientSecret = String.fromEnvironment('STRAVA_CLIENT_SECRET', defaultValue: '');
  
  static bool get hasStravaConfig => 
    stravaClientId.isNotEmpty && stravaClientSecret.isNotEmpty;
}
