name: Build and Release Applications

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
  STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          
      - name: Check if tag exists
        id: check_tag
        run: |
          TAG_EXISTS=$(git tag -l "$VERSION")
          if [[ "$TAG_EXISTS" == "$VERSION" ]]; then
            SUFFIX=1
            NEW_TAG="$VERSION-$SUFFIX"
            while [[ $(git tag -l "$NEW_TAG") == "$NEW_TAG" ]]; do
              SUFFIX=$((SUFFIX+1))
              NEW_TAG="$VERSION-$SUFFIX"
            done
            echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          else
            echo "NEW_TAG=$VERSION" >> $GITHUB_ENV
          fi
          
      - name: Set output
        id: set_version
        run: echo "::set-output name=version::$NEW_TAG"

  build-android:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - name: Create env.local.dart
        run: |
          mkdir -p lib/config
          umask 077
          cat > lib/config/env.local.dart << EOL
          class Environment {
            static const String stravaClientId = '${{ secrets.STRAVA_CLIENT_ID }}';
            static const String stravaClientSecret = '${{ secrets.STRAVA_CLIENT_SECRET }}';
            
            static bool get hasStravaConfig =>
              stravaClientId.isNotEmpty && stravaClientSecret.isNotEmpty;
          }
          EOL

      - name: Build Android APK
        run: flutter build apk --no-tree-shake-icons

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          mv build/app/outputs/flutter-apk/app-release.apk artifacts/ss2kconfigapp.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: artifacts/

  build-macos:
    needs: prepare
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      # Debug environment variables
      - name: Debug Environment Variables
        run: |
          echo "Checking environment variables (secrets will be masked):"
          env | grep -i STRAVA || true
          
      - name: Create env.local.dart
        run: |
          mkdir -p lib/config
          umask 077
          cat > lib/config/env.local.dart << EOL
          class Environment {
            static const String stravaClientId = '${{ secrets.STRAVA_CLIENT_ID }}';
            static const String stravaClientSecret = '${{ secrets.STRAVA_CLIENT_SECRET }}';
            
            static bool get hasStravaConfig =>
              stravaClientId.isNotEmpty && stravaClientSecret.isNotEmpty;
          }
          EOL
          
          # Verify file exists but don't show contents
          ls -l lib/config/env.local.dart

      - name: Build iOS App
        run: flutter build ios --release --no-codesign --no-tree-shake-icons

      - name: Build macOS App
        run: flutter build macos --release --no-tree-shake-icons

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          zip -r artifacts/ss2kconfigapp${{ needs.prepare.outputs.version }}.zip build/ios/iphoneos build/macos/Build/Products/Release

      # Clean up sensitive files
      - name: Clean up env.local.dart
        if: always()
        run: |
          if [ -f lib/config/env.local.dart ]; then
            rm lib/config/env.local.dart
            echo "Cleaned up env.local.dart"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: artifacts/

  build-linux:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.22.3'

      - name: Create env.local.dart
        run: |
          mkdir -p lib/config
          umask 077
          cat > lib/config/env.local.dart << EOL
          class Environment {
            static const String stravaClientId = '${{ secrets.STRAVA_CLIENT_ID }}';
            static const String stravaClientSecret = '${{ secrets.STRAVA_CLIENT_SECRET }}';
            
            static bool get hasStravaConfig =>
              stravaClientId.isNotEmpty && stravaClientSecret.isNotEmpty;
          }
          EOL

      - name: Set up QEMU
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Linux dependencies
        run: |
          sudo dpkg --add-architecture ${{ matrix.arch }}
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev:${{ matrix.arch }} libx11-dev:${{ matrix.arch }} pkg-config cmake ninja-build libblkid-dev:${{ matrix.arch }} liblzma-dev:${{ matrix.arch }} libsecret-1-dev:${{ matrix.arch }} libjsoncpp-dev:${{ matrix.arch }}
          sudo apt-get install -y libgstreamer1.0-dev:${{ matrix.arch }} libgstreamer-plugins-base1.0-dev:${{ matrix.arch }} libunwind-dev:${{ matrix.arch }}
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build Linux App
        run: |
          flutter config --enable-linux-desktop
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
            export CXX=aarch64-linux-gnu-g++
            flutter build linux --release --no-tree-shake-icons --target-platform=linux-arm64
          else
            flutter build linux --release --no-tree-shake-icons
          fi
          
      - name: Create Debian Package
        run: |
          # Create package directory structure
          mkdir -p debian/DEBIAN
          mkdir -p debian/usr/bin
          mkdir -p debian/usr/share/applications
          mkdir -p debian/usr/share/icons/hicolor/256x256/apps
          
          # Create control file
          cat > debian/DEBIAN/control << EOL
          Package: ss2kconfigapp
          Version: ${{ needs.prepare.outputs.version }}
          Section: utils
          Priority: optional
          Architecture: ${{ matrix.arch }}
          Maintainer: SmartSpin2k Team
          Description: SmartSpin2k Configuration Application
           A Flutter application for configuring and controlling SmartSpin2k devices.
          EOL
          
          # Copy application files based on architecture
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            cp -r build/linux/arm64/release/bundle/* debian/usr/bin/
          else
            cp -r build/linux/x64/release/bundle/* debian/usr/bin/
          fi
          
          # Copy icon
          cp assets/icons/ss2kv3.png debian/usr/share/icons/hicolor/256x256/apps/ss2kconfigapp.png
          
          # Create desktop file
          cat > debian/usr/share/applications/ss2kconfigapp.desktop << EOL
          [Desktop Entry]
          Name=SmartSpin2k Config App
          Exec=/usr/bin/ss2kconfigapp
          Icon=ss2kconfigapp
          Type=Application
          Categories=Utility;
          EOL
          
          # Set permissions
          chmod 755 debian/usr/bin/ss2kconfigapp
          chmod -R 755 debian/DEBIAN
          
          # Build the package with architecture in filename
          dpkg-deb --build debian ss2kconfigapp-${{ matrix.arch }}.deb

      - name: Create artifacts
        run: |
          mkdir -p artifacts
          mv ss2kconfigapp-${{ matrix.arch }}.deb artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: artifacts/

  create-release:
    needs: [prepare, build-android, build-macos, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all-artifacts

      - name: Prepare release bundle
        run: |
          mkdir -p release
          cp all-artifacts/android-artifacts/ss2kconfigapp.apk release/ss2kconfigapp-${{ needs.prepare.outputs.version }}.apk
          cp all-artifacts/macos-artifacts/ss2kconfigapp${{ needs.prepare.outputs.version }}.zip release/
          cp all-artifacts/linux-artifacts/ss2kconfigapp-amd64.deb release/ss2kconfigapp-${{ needs.prepare.outputs.version }}-amd64.deb
          cp all-artifacts/linux-artifacts/ss2kconfigapp-arm64.deb release/ss2kconfigapp-${{ needs.prepare.outputs.version }}-arm64.deb

      - name: Create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prepare.outputs.version }}
          name: SmartSpin2kConfigApp ${{ needs.prepare.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: true
          body: ${{ github.event.head_commit.message }}
          files: |
            release/ss2kconfigapp-${{ needs.prepare.outputs.version }}.apk
            release/ss2kconfigapp${{ needs.prepare.outputs.version }}.zip
            release/ss2kconfigapp-${{ needs.prepare.outputs.version }}-amd64.deb
            release/ss2kconfigapp-${{ needs.prepare.outputs.version }}-arm64.deb
